name = "MeinKraft"
author = "nih"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d62b0183ce94d919d55463e433da4773f2a98b129ebdcec18264b360cf462eab"

[versions]
fabric = "0.16.7"
minecraft = "1.21.1"
