name = "FairyRome"
author = "nih"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a65ad39b70ff7b492841ffe622f9dc60fc9fe2d8231c464567173706b815da22"

[versions]
fabric = "0.16.7"
minecraft = "1.21.1"
