name = "MeinKraft"
author = "nih"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "961d4eb688a85568e91e5b3aa427de229ed9a982cd3e01bca512b155db929f31"

[versions]
fabric = "0.16.7"
minecraft = "1.21.1"
